# Form implementation generated from reading ui file 'src/ui/constants_tab.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConstantsTab(object):
    def setupUi(self, ConstantsTab):
        ConstantsTab.setObjectName("ConstantsTab")
        ConstantsTab.resize(320, 240)
        self.gridLayout_2 = QtWidgets.QGridLayout(ConstantsTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_save = QtWidgets.QPushButton(parent=ConstantsTab)
        self.button_save.setObjectName("button_save")
        self.gridLayout_2.addWidget(self.button_save, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.rle_service_cost = ResetableLineEdit(parent=ConstantsTab)
        self.rle_service_cost.setObjectName("rle_service_cost")
        self.gridLayout.addWidget(self.rle_service_cost, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=ConstantsTab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.rle_full_tax = ResetableLineEdit(parent=ConstantsTab)
        self.rle_full_tax.setObjectName("rle_full_tax")
        self.gridLayout.addWidget(self.rle_full_tax, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=ConstantsTab)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.rle_lower_tax = ResetableLineEdit(parent=ConstantsTab)
        self.rle_lower_tax.setObjectName("rle_lower_tax")
        self.gridLayout.addWidget(self.rle_lower_tax, 2, 2, 1, 1)
        self.rle_vat_tax = ResetableLineEdit(parent=ConstantsTab)
        self.rle_vat_tax.setObjectName("rle_vat_tax")
        self.gridLayout.addWidget(self.rle_vat_tax, 5, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=ConstantsTab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=ConstantsTab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.rle_la_limit = ResetableLineEdit(parent=ConstantsTab)
        self.rle_la_limit.setObjectName("rle_la_limit")
        self.gridLayout.addWidget(self.rle_la_limit, 4, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=ConstantsTab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)

        self.retranslateUi(ConstantsTab)
        self.rle_service_cost.textEdited.connect(ConstantsTab.valueEdited) # type: ignore
        self.rle_full_tax.textEdited.connect(ConstantsTab.valueEdited) # type: ignore
        self.rle_lower_tax.textEdited.connect(ConstantsTab.valueEdited) # type: ignore
        self.rle_la_limit.textEdited.connect(ConstantsTab.valueEdited) # type: ignore
        self.rle_vat_tax.textEdited.connect(ConstantsTab.valueEdited) # type: ignore
        self.button_save.clicked.connect(ConstantsTab.saveData) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ConstantsTab)

    def retranslateUi(self, ConstantsTab):
        _translate = QtCore.QCoreApplication.translate
        ConstantsTab.setWindowTitle(_translate("ConstantsTab", "Form"))
        self.button_save.setText(_translate("ConstantsTab", "Uložiť"))
        self.label_2.setText(_translate("ConstantsTab", "Plna dan"))
        self.label_5.setText(_translate("ConstantsTab", "DPH"))
        self.label.setText(_translate("ConstantsTab", "Cena za liter"))
        self.label_3.setText(_translate("ConstantsTab", "Zlavnena dan"))
        self.label_4.setText(_translate("ConstantsTab", "Limit la"))
from widgets.resetable_line_edit import ResetableLineEdit
