# Form implementation generated from reading ui file 'src/ui/customers_tab.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CustomersTab(object):
    def setupUi(self, CustomersTab):
        CustomersTab.setObjectName("CustomersTab")
        CustomersTab.resize(681, 457)
        self.verticalLayout = QtWidgets.QVBoxLayout(CustomersTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vertical_name = QtWidgets.QVBoxLayout()
        self.vertical_name.setObjectName("vertical_name")
        self.label_name = QtWidgets.QLabel(parent=CustomersTab)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.vertical_name.addWidget(self.label_name)
        self.le_name = QtWidgets.QLineEdit(parent=CustomersTab)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.le_name.setFont(font)
        self.le_name.setObjectName("le_name")
        self.vertical_name.addWidget(self.le_name)
        self.horizontalLayout_2.addLayout(self.vertical_name)
        self.vertical_address = QtWidgets.QVBoxLayout()
        self.vertical_address.setObjectName("vertical_address")
        self.label_address = QtWidgets.QLabel(parent=CustomersTab)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_address.setFont(font)
        self.label_address.setObjectName("label_address")
        self.vertical_address.addWidget(self.label_address)
        self.le_address = QtWidgets.QLineEdit(parent=CustomersTab)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.le_address.setFont(font)
        self.le_address.setObjectName("le_address")
        self.vertical_address.addWidget(self.le_address)
        self.horizontalLayout_2.addLayout(self.vertical_address)
        self.vertical_birthday = QtWidgets.QVBoxLayout()
        self.vertical_birthday.setObjectName("vertical_birthday")
        self.label_birthday = QtWidgets.QLabel(parent=CustomersTab)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_birthday.setFont(font)
        self.label_birthday.setObjectName("label_birthday")
        self.vertical_birthday.addWidget(self.label_birthday)
        self.le_birthday = QtWidgets.QLineEdit(parent=CustomersTab)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.le_birthday.setFont(font)
        self.le_birthday.setObjectName("le_birthday")
        self.vertical_birthday.addWidget(self.le_birthday)
        self.horizontalLayout_2.addLayout(self.vertical_birthday)
        self.vertical_phone_number = QtWidgets.QVBoxLayout()
        self.vertical_phone_number.setObjectName("vertical_phone_number")
        self.label_phone_number = QtWidgets.QLabel(parent=CustomersTab)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_phone_number.setFont(font)
        self.label_phone_number.setObjectName("label_phone_number")
        self.vertical_phone_number.addWidget(self.label_phone_number)
        self.le_phone_number = QtWidgets.QLineEdit(parent=CustomersTab)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.le_phone_number.setFont(font)
        self.le_phone_number.setObjectName("le_phone_number")
        self.vertical_phone_number.addWidget(self.le_phone_number)
        self.horizontalLayout_2.addLayout(self.vertical_phone_number)
        self.vertical_season = QtWidgets.QVBoxLayout()
        self.vertical_season.setObjectName("vertical_season")
        self.label_4 = QtWidgets.QLabel(parent=CustomersTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.vertical_season.addWidget(self.label_4)
        self.seasonSelect = SeasonSelect(parent=CustomersTab)
        self.seasonSelect.setObjectName("seasonSelect")
        self.vertical_season.addWidget(self.seasonSelect)
        self.horizontalLayout_2.addLayout(self.vertical_season)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.customer_table = QtWidgets.QTableView(parent=CustomersTab)
        self.customer_table.setObjectName("customer_table")
        self.verticalLayout.addWidget(self.customer_table)

        self.retranslateUi(CustomersTab)
        self.le_name.textEdited['QString'].connect(CustomersTab.name_edited) # type: ignore
        self.le_address.textEdited['QString'].connect(CustomersTab.address_edited) # type: ignore
        self.le_birthday.textEdited['QString'].connect(CustomersTab.birthday_edited) # type: ignore
        self.le_phone_number.textEdited['QString'].connect(CustomersTab.phone_number_edited) # type: ignore
        self.seasonSelect.seasonSelected['int'].connect(CustomersTab.season_selected) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CustomersTab)

    def retranslateUi(self, CustomersTab):
        _translate = QtCore.QCoreApplication.translate
        CustomersTab.setWindowTitle(_translate("CustomersTab", "Form"))
        self.label_name.setText(_translate("CustomersTab", "Meno a priezvisko:"))
        self.label_address.setText(_translate("CustomersTab", "Adresa:"))
        self.label_birthday.setText(_translate("CustomersTab", "Dátum nar.:"))
        self.label_phone_number.setText(_translate("CustomersTab", "Tel. číslo:"))
        self.label_4.setText(_translate("CustomersTab", "Sezóna:"))
from widgets.season_select import SeasonSelect
