# Form implementation generated from reading ui file 'src/ui/distillings_tab.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DistillingsTab(object):
    def setupUi(self, DistillingsTab):
        DistillingsTab.setObjectName("DistillingsTab")
        DistillingsTab.resize(592, 341)
        self.verticalLayout = QtWidgets.QVBoxLayout(DistillingsTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView = QtWidgets.QTableView(parent=DistillingsTab)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)

        self.retranslateUi(DistillingsTab)
        QtCore.QMetaObject.connectSlotsByName(DistillingsTab)

    def retranslateUi(self, DistillingsTab):
        _translate = QtCore.QCoreApplication.translate
        DistillingsTab.setWindowTitle(_translate("DistillingsTab", "DistillingsTab"))
