# Form implementation generated from reading ui file 'src/ui/distilling_input.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_distilling_input(object):
    def setupUi(self, distilling_input):
        distilling_input.setObjectName("distilling_input")
        distilling_input.resize(1262, 122)
        self.horizontalLayout = QtWidgets.QHBoxLayout(distilling_input)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_ferment_volume = QtWidgets.QLineEdit(parent=distilling_input)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.edit_ferment_volume.setFont(font)
        self.edit_ferment_volume.setObjectName("edit_ferment_volume")
        self.horizontalLayout.addWidget(self.edit_ferment_volume)
        self.edit_ferment_type = QtWidgets.QLineEdit(parent=distilling_input)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.edit_ferment_type.setFont(font)
        self.edit_ferment_type.setObjectName("edit_ferment_type")
        self.horizontalLayout.addWidget(self.edit_ferment_type)
        self.edit_alcohol_volume = QtWidgets.QLineEdit(parent=distilling_input)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.edit_alcohol_volume.setFont(font)
        self.edit_alcohol_volume.setObjectName("edit_alcohol_volume")
        self.horizontalLayout.addWidget(self.edit_alcohol_volume)
        self.edit_alcohol_percentage = QtWidgets.QLineEdit(parent=distilling_input)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.edit_alcohol_percentage.setFont(font)
        self.edit_alcohol_percentage.setObjectName("edit_alcohol_percentage")
        self.horizontalLayout.addWidget(self.edit_alcohol_percentage)
        self.edit_alcohol_temperature = QtWidgets.QLineEdit(parent=distilling_input)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.edit_alcohol_temperature.setFont(font)
        self.edit_alcohol_temperature.setObjectName("edit_alcohol_temperature")
        self.horizontalLayout.addWidget(self.edit_alcohol_temperature)
        self.edit_alcohol_percentage_at_20 = QtWidgets.QLineEdit(parent=distilling_input)
        self.edit_alcohol_percentage_at_20.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.edit_alcohol_percentage_at_20.setFont(font)
        self.edit_alcohol_percentage_at_20.setReadOnly(True)
        self.edit_alcohol_percentage_at_20.setClearButtonEnabled(False)
        self.edit_alcohol_percentage_at_20.setObjectName("edit_alcohol_percentage_at_20")
        self.horizontalLayout.addWidget(self.edit_alcohol_percentage_at_20)
        self.edit_alcohol_volume_la = QtWidgets.QLineEdit(parent=distilling_input)
        self.edit_alcohol_volume_la.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.edit_alcohol_volume_la.setFont(font)
        self.edit_alcohol_volume_la.setReadOnly(True)
        self.edit_alcohol_volume_la.setObjectName("edit_alcohol_volume_la")
        self.horizontalLayout.addWidget(self.edit_alcohol_volume_la)
        self.edit_lower_tax = QtWidgets.QLineEdit(parent=distilling_input)
        self.edit_lower_tax.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.edit_lower_tax.setFont(font)
        self.edit_lower_tax.setReadOnly(True)
        self.edit_lower_tax.setObjectName("edit_lower_tax")
        self.horizontalLayout.addWidget(self.edit_lower_tax)
        self.edit_full_tax = QtWidgets.QLineEdit(parent=distilling_input)
        self.edit_full_tax.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.edit_full_tax.setFont(font)
        self.edit_full_tax.setReadOnly(True)
        self.edit_full_tax.setObjectName("edit_full_tax")
        self.horizontalLayout.addWidget(self.edit_full_tax)
        self.edit_sum_tax = QtWidgets.QLineEdit(parent=distilling_input)
        self.edit_sum_tax.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.edit_sum_tax.setFont(font)
        self.edit_sum_tax.setReadOnly(True)
        self.edit_sum_tax.setObjectName("edit_sum_tax")
        self.horizontalLayout.addWidget(self.edit_sum_tax)
        self.delete_line_button = QtWidgets.QPushButton(parent=distilling_input)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.delete_line_button.setFont(font)
        self.delete_line_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/trash-can.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.delete_line_button.setIcon(icon)
        self.delete_line_button.setObjectName("delete_line_button")
        self.horizontalLayout.addWidget(self.delete_line_button)

        self.retranslateUi(distilling_input)
        self.edit_ferment_volume.textEdited['QString'].connect(distilling_input.update_values) # type: ignore
        self.edit_ferment_type.textEdited['QString'].connect(distilling_input.update_values) # type: ignore
        self.edit_alcohol_volume.textEdited['QString'].connect(distilling_input.update_values) # type: ignore
        self.edit_alcohol_percentage.textEdited['QString'].connect(distilling_input.update_values) # type: ignore
        self.edit_alcohol_temperature.textEdited['QString'].connect(distilling_input.update_values) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(distilling_input)

    def retranslateUi(self, distilling_input):
        _translate = QtCore.QCoreApplication.translate
        distilling_input.setWindowTitle(_translate("distilling_input", "Form"))
