# Form implementation generated from reading ui file 'src/ui/resetable_line_edit.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ResetableLineEdit(object):
    def setupUi(self, ResetableLineEdit):
        ResetableLineEdit.setObjectName("ResetableLineEdit")
        ResetableLineEdit.resize(202, 50)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ResetableLineEdit)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=ResetableLineEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setInputMask("")
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.reset_button = QtWidgets.QPushButton(parent=ResetableLineEdit)
        self.reset_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_button.sizePolicy().hasHeightForWidth())
        self.reset_button.setSizePolicy(sizePolicy)
        self.reset_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/undo_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.reset_button.setIcon(icon)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout.addWidget(self.reset_button)

        self.retranslateUi(ResetableLineEdit)
        QtCore.QMetaObject.connectSlotsByName(ResetableLineEdit)

    def retranslateUi(self, ResetableLineEdit):
        _translate = QtCore.QCoreApplication.translate
        ResetableLineEdit.setWindowTitle(_translate("ResetableLineEdit", "Form"))
