# Form implementation generated from reading ui file 'src/ui/season_select_widget.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SeasonSelectCB(object):
    def setupUi(self, SeasonSelectCB):
        SeasonSelectCB.setObjectName("SeasonSelectCB")
        SeasonSelectCB.resize(229, 182)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SeasonSelectCB)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(parent=SeasonSelectCB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)

        self.retranslateUi(SeasonSelectCB)
        self.comboBox.currentIndexChanged['int'].connect(SeasonSelectCB.cbChanged) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SeasonSelectCB)

    def retranslateUi(self, SeasonSelectCB):
        _translate = QtCore.QCoreApplication.translate
        SeasonSelectCB.setWindowTitle(_translate("SeasonSelectCB", "Form"))
