# Form implementation generated from reading ui file 'src/ui/season_edit_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SeasonDialog(object):
    def setupUi(self, SeasonDialog):
        SeasonDialog.setObjectName("SeasonDialog")
        SeasonDialog.resize(320, 240)
        self.gridLayout = QtWidgets.QGridLayout(SeasonDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.dateEdit_start = QtWidgets.QDateEdit(parent=SeasonDialog)
        self.dateEdit_start.setCalendarPopup(True)
        self.dateEdit_start.setObjectName("dateEdit_start")
        self.gridLayout.addWidget(self.dateEdit_start, 1, 1, 1, 1)
        self.button_delete = QtWidgets.QPushButton(parent=SeasonDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button_delete.setFont(font)
        self.button_delete.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/trash-can.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.button_delete.setIcon(icon)
        self.button_delete.setObjectName("button_delete")
        self.gridLayout.addWidget(self.button_delete, 3, 1, 1, 1)
        self.button_save = QtWidgets.QPushButton(parent=SeasonDialog)
        self.button_save.setObjectName("button_save")
        self.gridLayout.addWidget(self.button_save, 3, 2, 1, 1)
        self.dateEdit_end = QtWidgets.QDateEdit(parent=SeasonDialog)
        self.dateEdit_end.setCalendarPopup(True)
        self.dateEdit_end.setObjectName("dateEdit_end")
        self.gridLayout.addWidget(self.dateEdit_end, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=SeasonDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=SeasonDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)

        self.retranslateUi(SeasonDialog)
        self.button_delete.clicked.connect(SeasonDialog.delete) # type: ignore
        self.button_save.clicked.connect(SeasonDialog.save) # type: ignore
        self.dateEdit_start.editingFinished.connect(SeasonDialog.set_start) # type: ignore
        self.dateEdit_end.editingFinished.connect(SeasonDialog.set_end) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SeasonDialog)
        SeasonDialog.setTabOrder(self.dateEdit_start, self.dateEdit_end)
        SeasonDialog.setTabOrder(self.dateEdit_end, self.button_delete)
        SeasonDialog.setTabOrder(self.button_delete, self.button_save)

    def retranslateUi(self, SeasonDialog):
        _translate = QtCore.QCoreApplication.translate
        SeasonDialog.setWindowTitle(_translate("SeasonDialog", "SeasonDialog"))
        self.dateEdit_start.setDisplayFormat(_translate("SeasonDialog", "d.M.yyyy"))
        self.button_save.setText(_translate("SeasonDialog", "Uložiť"))
        self.dateEdit_end.setDisplayFormat(_translate("SeasonDialog", "d.M.yyyy"))
        self.label.setText(_translate("SeasonDialog", "Začiatok"))
        self.label_2.setText(_translate("SeasonDialog", "Koniec"))
