# Form implementation generated from reading ui file 'src/ui/seasons_tab.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SeasonsTab(object):
    def setupUi(self, SeasonsTab):
        SeasonsTab.setObjectName("SeasonsTab")
        SeasonsTab.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(SeasonsTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_new_season = QtWidgets.QPushButton(parent=SeasonsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_new_season.sizePolicy().hasHeightForWidth())
        self.button_new_season.setSizePolicy(sizePolicy)
        self.button_new_season.setObjectName("button_new_season")
        self.horizontalLayout.addWidget(self.button_new_season)
        self.buttonRefresh = QtWidgets.QPushButton(parent=SeasonsTab)
        self.buttonRefresh.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonRefresh.sizePolicy().hasHeightForWidth())
        self.buttonRefresh.setSizePolicy(sizePolicy)
        self.buttonRefresh.setSizeIncrement(QtCore.QSize(1, 1))
        self.buttonRefresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/ui/../../resources/undo_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buttonRefresh.setIcon(icon)
        self.buttonRefresh.setCheckable(False)
        self.buttonRefresh.setAutoDefault(False)
        self.buttonRefresh.setDefault(False)
        self.buttonRefresh.setFlat(False)
        self.buttonRefresh.setObjectName("buttonRefresh")
        self.horizontalLayout.addWidget(self.buttonRefresh)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table_seasons = QtWidgets.QTableView(parent=SeasonsTab)
        self.table_seasons.setObjectName("table_seasons")
        self.verticalLayout.addWidget(self.table_seasons)

        self.retranslateUi(SeasonsTab)
        self.button_new_season.clicked.connect(SeasonsTab.season_create) # type: ignore
        self.table_seasons.doubleClicked['QModelIndex'].connect(SeasonsTab.season_selected) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SeasonsTab)

    def retranslateUi(self, SeasonsTab):
        _translate = QtCore.QCoreApplication.translate
        SeasonsTab.setWindowTitle(_translate("SeasonsTab", "SeasonsTab"))
        self.button_new_season.setText(_translate("SeasonsTab", "Nová Sezóna"))
